export const projects = [
  {
    title: 'Realtor',
    description: "this is a React real estate application that allows users to search for rental as well as sale properties, read the description and features such as amenities that each property offers, and use advanced filters to filter properties based on their needs.",
    image: 'images/realtor.jpg',
    tags: ['React', 'Next.js'],
    source: 'https://github.com/pjfooeve09/realtor',
    visit: '',
    id: 2,
  },
  {
    title: 'Recipe Finder',
    description: "This App allows users to browse through popular and vegetarian recipes. In addition, they can search for a recipe and open a list of recipes based on the recipe category. Instructions and ingredients will be displayed to the user for each recipe.",
    image: 'images/recipe3.jpg',
    tags: ['React'],
    source: 'https://github.com/pjfooeve09/delicious-recipe',
    visit: '',
    id: 1,
  },
  {
    title: 'Superhero World',
    description: 'This MVC Rails app allows users to create an account and login (as well as login with Facebook). The user can then perform all the CRUD actions on a team with superheroes, and display the team with the most superheroes.',
    image: 'images/superhero.jpg',
    tags: ['Ruby on Rails'],
    source: 'https://github.com/pjfooeve09/superhero_world',
    visit: '',
    id: 3,
  },
  // {
  //   title: 'Sinatra Hospital Maker',
  //   description: "This MVC Sinatra application allows users to create signup and login to their account. Once logged in, the user can create a hospital based on hospital's name and hospital's country and can also view a list of all the hospitals created. Once a hospital is added, it can only be edited and deleted by the user who originally added the hospital.",
  //   image: 'images/sinatrahospital.jpg',
  //   tags: ['Sinatra (Ruby)'],
  //   source: 'https://github.com/pjfooeve09/sinatra-hospital-maker',
  //   visit: 'https://www.youtube.com/watch?v=FxAuq6qN0nI&t=121s&ab_channel=ParhamJavadi',
  //   id: 5,
  // },
  {
    title: 'Task Tracker',
    description: "This Vue.js app allows users to create, view, edit, and delete a task, and set a reminder for each task.",
    image: 'images/tasktracker.jpg',
    tags: ['Vue.js', 'HTML', 'CSS'],
    source: 'https://github.com/pjfooeve09/task-tracker',
    visit: '',
    id: 4,
  },
];

export const TimeLineData = [
  { year: 2016, text: 'Started my journey as a new developer.', },
  { year: 2017, text: 'Worked intensively on ROMs & Kernels.', },
  { year: 2018, text: 'Learned Android app development.', },
  { year: 2019, text: 'Finished Diploma in Computer Engineering.', },
  { year: 2020, text: 'Got a scholarship from the Delhi government.', },
  { year: 2021, text: 'Still trying to figure out this weird year.', },
];